services:
  redis:
    image: redis:alpine
    ports:
      - 6789:6789

  db:
    image: postgres:latest
    restart: unless-stopped 
    environment:
      POSTGRES_PASSWORD: examples
    ports:
    - 5433:5432
